DROP DATABASE IF EXISTS papeleria;
CREATE DATABASE papeleria;
USE papeleria;


CREATE TABLE IF NOT EXISTS Providers (
	ID_Provider INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(20) NOT NULL,
	categoria ENUM('revistas', 'bolis', 'hojas', 'pegamento') NOT NULL,
	tlf INTEGER(9) NOT NULL,
	direccion VARCHAR(40) NOT NULL


);
CREATE TABLE IF NOT EXISTS Stock (

	ID_Product INTEGER PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(20) NOT NULL,
	cantidad INTEGER(3) UNSIGNED NOT NULL,
	precio INT(5) UNSIGNED NOT NULL,
	ID_Provider VARCHAR(15) FOREIGN KEY (ID_Provider) REFERENCES Providers(ID_Provider)

);

CREATE TABLE IF NOT EXISTS Billing (
	ID_Bill INTEGER PRIMARY KEY AUTO_INCREMENT,
	fecha DATETIME CURRENT_TIMESTAMP NOT NULL,
	cantidad INTEGER(3) UNSIGNED NOT NULL,
	coste DOUBLE(5,2) UNSIGNED NOT NULL

);
CREATE TABLE IF NOT EXISTS Client (

	ID_Client INTEGER PRIMARY KEY AUTO_INCREMENT,
	clientName VARCHAR(20) NOT NULL,
	DNI VARCHAR(9) NOT NULL,
	tlf INTEGER(9),
	direccion VARCHAR(30)

);

CREATE TABLE IF NOT EXISTS Tickets (
	ID_Ticket INTEGER PRIMARY KEY AUTO_INCREMENT,
	ID_Product VARCHAR(15) FOREIGN KEY (ID_Product) REFERENCES Stock(ID_Product),
	ID_Bill VARCHAR(15) FOREIGN KEY (ID_Bill) REFERENCES Billing(ID_Bill),
	ID_Client VARCHAR(15) FOREIGN KEY (ID_Client) REFERENCES Client(ID_Client) DEFAULT NULL
	

);

